import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    width: "98%",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  columnContainer: {
    flex: 1,
    marginTop: 10,
    marginLeft: 10,

    justifyContent: "center",
    alignItems: "center",
   
    backgroundColor: "#6e78ff",
    
    width: "50%",
    height: 100,
    borderRadius: 10,
  },
  columnContainer2: {
    flex: 1,
   
    marginLeft: 8,
   
    justifyContent: "center",
    alignItems: "center",

    backgroundColor: "#6e78ff",
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    width: "50%",
    height: 100,
    borderRadius: 10,
    marginTop:9,
  },
  columnContainer3: {
    flex: 1,
    marginTop: 10,
    flexDirection: 'row',
    marginLeft: 10,
    justifyContent: "center",
    alignItems: "center",

    backgroundColor: "#6e78ff",
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    width: "50%",
    height: 100,
    borderRadius: 10,
  },
  columnContainer4: {
    flex: 1,
    marginTop: 10,
    marginLeft: 10,
    justifyContent: "center",
    alignItems: "center",

    backgroundColor: "red",
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    width: "100%",
    height: 90,
    borderRadius: 10,
  },
  error: {
    color: "red",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
  title2:{
   fontSize:12,
   color:"#fff"
  },
  input: {
    width: "90%",
    height: 40,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  button: {
    backgroundColor: "#7286D3",
    width: "90%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    marginBottom: 25,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  registerText: {
    color: "grey",
    marginBottom: 90,
  },
  register: {
    color: "#116A7B",
  },
  radioContainer: {
    backgroundColor: "red",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  radioButton: {
    marginRight: 10,
    color: "grey",
  },
  radioContainer: {
    marginBottom: 10,
    borderBlockColor: "grey",
  },
  radioButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    color: "grey",
  },
  uploadbutton: {
    borderWidth: 2,
    backgroundColor: "#B3B3B3",
    width: "90%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    marginBottom: 25,
    color: "#7286D3",
    borderColor: "#7286D3",
  },
  containerCandidate: {
    flex: 1,marginTop:10,
    marginLeft:10,
  
  },
  mainCardView: {
    height: 90,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 15,
    shadowColor: 'grey',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 14,
    marginTop: 6,
    marginBottom: 6,
    marginLeft: 16,
    marginRight: 16,
  },
  subCardView: {
    height: 50,
    width: 50,
    borderRadius: 25,
    backgroundColor: 'grey',
    borderColor: 'grey0',
    borderWidth: 1,
    borderStyle: 'solid',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
